bazel_dep(name = "aspect_rules_esbuild", version = "0.27.0")
bazel_dep(name = "aspect_rules_js", version = "3.4.1")
bazel_dep(name = "aspect_rules_jest", version = "0.26.0")
bazel_dep(name = "aspect_rules_py", version = "2.0.0-alpha.6")
bazel_dep(name = "aspect_rules_ts", version = "3.10.1")
bazel_dep(name = "bazel_lib", version = "3.7.2")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "grpc", version = "1.83.0")
bazel_dep(name = "jq.bzl", version = "0.6.1")
bazel_dep(name = "llvm", version = "0.8.19")
bazel_dep(name = "openssl", version = "4.0.1.bcr.0")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "protobuf", version = "36.1.bcr.1")
bazel_dep(name = "riegeli", version = "0.0.0-20250822-9f2744d")
bazel_dep(name = "rules_helm", version = "0.31.0")
bazel_dep(name = "rules_kustomize", version = "0.5.3")
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_proto_grpc_python", version = "5.8.0")
bazel_dep(name = "tar.bzl", version = "0.10.8")

single_version_override(
    module_name = "envoy_api",
    version = "0.0.0-20260130-84e8436",
)

single_version_override(
    module_name = "grpc",
    patch_strip = 0,
    patches = ["//patches:grpc_remove_py_libs.patch"],
)

single_version_override(
    module_name = "highwayhash",
    version = "0.0.0-20240305-5ad3bf8.bcr.1",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_archive(
    name = "sws_linux_amd64",
    build_file_content = 'exports_files(["static-web-server"])',
    sha256 = "804bc0c31c78385ac04e9a36f3c2aa3d3170eb77d66807c2a1660c56b2026bb1",
    strip_prefix = "static-web-server-v2.44.0-x86_64-unknown-linux-musl",
    urls = ["https://github.com/static-web-server/static-web-server/releases/download/v2.44.0/static-web-server-v2.44.0-x86_64-unknown-linux-musl.tar.gz"],
)

http_archive(
    name = "sws_linux_arm64",
    build_file_content = 'exports_files(["static-web-server"])',
    sha256 = "e9d6bd0b05dea441028eb4e690249ab585d711b311646bf9f420fcea01449670",
    strip_prefix = "static-web-server-v2.44.0-aarch64-unknown-linux-musl",
    urls = ["https://github.com/static-web-server/static-web-server/releases/download/v2.44.0/static-web-server-v2.44.0-aarch64-unknown-linux-musl.tar.gz"],
)

http_file(
    name = "tailwindcss_linux_amd64",
    downloaded_file_path = "tailwindcss",
    executable = True,
    sha256 = "dc61b3ac6b8c9ca874c0cc4c57b2409791a64c5540404ca5f5367360babc313a",
    urls = ["https://github.com/tailwindlabs/tailwindcss/releases/download/v4.3.3/tailwindcss-linux-x64"],
)

http_file(
    name = "tailwindcss_linux_arm64",
    downloaded_file_path = "tailwindcss",
    executable = True,
    sha256 = "55fd0b241214eff3de1e8ee4f22796662f2d2e7a49bcfca7477cfd0bac398195",
    urls = ["https://github.com/tailwindlabs/tailwindcss/releases/download/v4.3.3/tailwindcss-linux-arm64"],
)

interpreters = use_extension("@aspect_rules_py//py:extensions.bzl", "python_interpreters")
interpreters.toolchain(
    python_version = "3.12",
)
use_repo(interpreters, "python_interpreters")

uv = use_extension("@aspect_rules_py//uv:extensions.bzl", "uv")
uv.declare_hub(hub_name = "pypi")
uv.project(
    hub_name = "pypi",
    lock = "//:uv.lock",
    pyproject = "//:pyproject.toml",
)
use_repo(uv, "pypi")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "distroless_cc",
    digest = "sha256:e5d81ddde149641e2a9ba55be4545bc125c67de07508b03ba4c22e6eb0ded5aa",
    image = "gcr.io/distroless/cc-debian12",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
use_repo(
    oci,
    "distroless_cc",
    "distroless_cc_linux_amd64",
    "distroless_cc_linux_arm64_v8",
)

################
## Typescript ##
################

npm = use_extension(
    "@aspect_rules_js//npm:extensions.bzl",
    "npm",
    dev_dependency = True,
)
npm.npm_translate_lock(
    name = "npm",
    data = ["//:package.json"],
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
)
use_repo(npm, "npm")

rules_typescript = use_extension(
    "@aspect_rules_ts//ts:extensions.bzl",
    "typescript",
    dev_dependency = True,
)
rules_typescript.deps()
use_repo(rules_typescript, "npm_typescript")

##########
## Helm ##
##########

helm_import_repository = use_repo_rule(
    "@rules_helm//helm:helm_import.bzl",
    "helm_import_repository",
)

helm_import_repository(
    name = "envoy_gateway_chart",
    url = "oci://registry-1.docker.io/envoyproxy/gateway-helm:v1.9.0",
)

################
## Toolchains ##
################

register_toolchains(
    "@llvm//toolchain:all",
    "@python_interpreters//:all",
    "//client/toolchains:all",
)
