[tool.black]
line-length = 88
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | bazel-*
)/
|truescrub/proto/game_state_pb2\.pyi?
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["bazel-*", "truescrub/proto/game_state_pb2.py", "truescrub/proto/game_state_pb2.pyi"]

[tool.ruff]
line-length = 88
target-version = "py38"
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    "bazel-*",
    "venv",
    "truescrub/proto/game_state_pb2.py",
    "truescrub/proto/game_state_pb2.pyi",
]

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "W",    # pycodestyle warnings
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
]
ignore = [
    "E501",  # line too long (covered by black)
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports in __init__.py
"tests/*" = ["E501"]  # Line length in tests

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
follow_imports = "silent"

# Exclude generated files and third-party code
exclude = [
    "bazel-*",
    "truescrub/proto/game_state_pb2.py",
    "truescrub/proto/game_state_pb2.pyi",
]

# Previously test files had less strict typing - now all code has strict typing
# No overrides required anymore!

[[tool.mypy.overrides]]
module = "truescrub.proto.*"
ignore_missing_imports = true



[[tool.mypy.overrides]]
module = "google.protobuf.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "trueskill.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "deap.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "waitress.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pkg_resources"
ignore_missing_imports = true