apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: truescrub-client
        env:
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
