apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/client
  - ../../apps/truescrub
  - namespace.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - gateway_helm.yaml

secretGenerator:
  - name: external-tls-secret
    namespace: envoy-gateway-system
    type: kubernetes.io/tls
    options:
      disableNameSuffixHash: true
    files:
      - tls.crt=tls.crt
      - tls.key=tls.key
  - name: truescrub
    namespace: truescrub
    literals:
      - shared-key=dev-secret-key
